### ISSUE TITLE
Connect with REST Countries and save data

### ISSUE THREAD

**Issue by przemgk** [przemgk/Frontend-Mentor#12]
**Tasks to do:**
- [x] Add and configure axios
- [x] Save data to context
- [x] Print data at home page
- [x] Rebuild Card component to redirect to details page
- [x] Read real data in details page
- [x] Rubuid proccess of getting data from API
