### ISSUE TITLE
Visual adjustments

### ISSUE THREAD

**Issue by przemgk** [przemgk/Frontend-Mentor#13]
**Tasks to do:**
- [x] Fix FlagBox white/black bar in Card component and set min width and height
- [x] Set new dimensions of Card component (more space)
- [x] Fix dropdown placement (currently hidden under Card)
- [x] Format population number
- [x] Add empty state for capital
- [x] Add empty state for border countries
