### ISSUE TITLE
Optimize loading proccess

### ISSUE THREAD

**Issue by przemgk** [przemgk/Frontend-Mentor#14]
**Task to do: **
- [ ] Limit unnecessary data downloads (e.g. use storage to save data at home page)
- [ ] Add preloader when download proccess need more time
- [ ] Create preloader component
