### ISSUE TITLE
Initialize project

### ISSUE THREAD

**Issue by przemgk** [przemgk/Frontend-Mentor#2]
**Tasks to do:**

- [x] Setup React App
- [x] Configure ESLint
- [x] Configure Prettier
- [x] Configure Husky and Lint-staged
- [x] Install styled-components
- [x] Configure Storybook
