### ISSUE TITLE
Create atoms

### ISSUE THREAD

**Issue by przemgk** [przemgk/Frontend-Mentor#3]
**Tasks to do:**
- [x] Create styled-components global styles
- [x] Add global styles to storybook
- [x] Add global variables
- [x] Create Paragraph component
- [x] Create Strong component
- [x] Create Heading component
- [x] Create Button component
- [x] Create SearchInput component
- [x] Create Dropdown component
- [x] Create FlagBox component
- [x] Add interactions to selected components
