### ISSUE TITLE
Add and configure React Router

### ISSUE THREAD

**Issue by przemgk** [przemgk/Frontend-Mentor#8]
**Tasks to do:**
- [x] Create MainTemplate and prepare routing addresses for: region, single country page, 404 page and home page
- [x] Prepare ModalTemplate, MenuBarTemplate, ListTemplate, DetailsTemplate
- [x] Add 404 page
- [x] Add home page
- [x] Add Links to Dropdown Component
- [x] Fix components backgrounds and hover states
- [x] Add details page
- [x] Fix errors with 404 page
